### ISSUE TITLE
ユーザ識別に用いる固有番号

### ISSUE THREAD

**Issue by af12066** [tonkatu05/BeaconReminder#10]
MAC アドレスの場合の取得方法は http://blog.livedoor.jp/shizuku_kun/archives/51456972.html
- ただし [**API Level 23 だと自分のアドレスが取得できない**](https://kazyx.blogspot.jp/2015/08/android-m-local-device-id.html)らしい
- 今回は API Level 19 を想定しているのでとりあえず試してみます

上記がダメだったら [ANDROID_ID](https://thinkit.co.jp/story/2012/03/09/3467?page=0%2C2) を試します。

それでもダメだったら...どうしましょう?

**Comment by ykokw** [comment]
https://developer.android.com/reference/java/util/UUID.html

**Comment by af12066** [comment]
解決しました
